
INSERT INTO users ( name, email, password)
VALUES ( 'Devin Sanders',
         'tristanjacobs@gmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
          ( 'Iva Harrison',
         'allisonjackson@mail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
          ( 'Lloyd Jefferson',
         'asherpoole@gmx.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
          ( 'Dale Coleman',
         'michaelgray@mail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Alejandro Osborne',
         'ariaatkinson@outlook.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Nell Medina',
         'juliansantos@aol.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Estelle Walsh',
         'elistanton@yahoo.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Herbert Graves',
         'emilyowen@live.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'John Stevens',
         'charliebattle@yahoo.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Isabelle Robbins',
         'miasutton@aol.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Jerome Wright',
         'bellaanthony@gmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'May Barrett',
         'gabriellabarrera@aol.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Christine Buchanan',
         'nathannguyen@ymail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Oscar Little',
         'alainamcfarland@hotmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Mabelle Hughes',
         'jordansears@outlook.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Adelaide Harrington',
         'ariawolfe@outlook.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Ola Brock',
         'alainajames@gmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Gavin Cook',
         'nolanbriggs@gmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Harriett Alvarez',
         'kaelynross@gmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Effie Simpson',
         'muhammadwebb@hotmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Mamie Webster',
         'ianhale@ymail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Jennie Powers',
         'lilabell@live.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Maggie Norris',
         'miafletcher@inbox.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Justin Reyes',
         'austindotson@aol.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Effie Phillips',
         'evelynaustin@ymail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Travis Mendoza',
         'lucypittman@gmx.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Edgar Harrison',
         'keiragates@ymail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Delia Caldwell',
         'elliotbaker@yahoo.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Calvin Thornton',
         'rileyrichard@outlook.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Elizabeth Lane',
         'henryhaynes@gmx.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'James Banks',
         'sydneylopez@live.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Micheal Page',
         'kennedyparks@mail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Owen Powell',
         'ariagallagher@gmail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Rosetta Walsh',
         'kylierhodes@mail.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Louis Washington',
         'chloecarter@google.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
         ( 'Pauline Cruz',
         'hannahpickett@inbox.com',
         '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');